- clean: ['~']

- link:
    ~/.config/terminator/config: terminator/config
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.npmrc: npm/npmrc
    ~/.vim: vim/vim
    ~/.vimrc: vim/vimrc
    ~/.wp: wp
    ~/.zsh: zsh/zsh
    ~/.zshrc: zsh/zshrc

- shell:
  - vim +PluginInstall +qall
