- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.config/terminator/config:
      create: true
      path: terminator/config
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.imwheelrc: imwheel/imwheelrc
    ~/.npmrc: npm/npmrc
    ~/.vim: vim/vim
    ~/.vimrc: vim/vimrc
    ~/.dotfiles/zsh/zsh/custom/themes/spaceship.zsh-theme: zsh/zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
    ~/.zsh: zsh/zsh
    ~/.zshrc: zsh/zshrc

- shell:
  - [vim +PluginInstall +qall, Installing vim plugins...]
  - [./bin/code-install-extensions, Installing VS Code extensions...]
  - [./bin/wp-cli-install, Installing WP-CLI...]
  - [./bin/psysh-install, Installing PsySH...]
