- clean: ['~']

- link:
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.npmrc: npm/npmrc
    ~/.vimrc: vim/vimrc
    ~/.vim: vim/vim

- shell:
  - git submodule update --init --recursive
  - vim +PluginInstall +qall
