# Path to your oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# Theme
#ZSH_THEME="miloshadzic"
ZSH_THEME="spaceship"

# Use case-sensitive completion
CASE_SENSITIVE="true"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.zsh/custom/

# Plugins
plugins=(git gitignore cp command-not-found rsync wp-cli github httpie)

# Initialize the oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Dotfiles PATH
DOTFILES=$HOME/.dotfiles

# User configuration
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$DOTFILES/bin:/snap/bin:$HOME/.local/bin:$HOME/Projects/slic"

# Editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='vim'
fi

# Aliases
if [ -f $HOME/.zsh/aliases.zsh ]; then
  . $HOME/.zsh/aliases.zsh
fi

# Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
