# Path to your oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# Theme
#ZSH_THEME="miloshadzic"
ZSH_THEME="spaceship"

# Use case-sensitive completion
CASE_SENSITIVE="true"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.zsh/custom/

# Plugins
plugins=(git gitignore cp command-not-found rsync wp-cli github httpie)

# Initialize the oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Dotfiles PATH
DOTFILES=$HOME/.dotfiles

# User configuration
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$DOTFILES/bin:/snap/bin:$HOME/.local/bin"

# Editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='vim'
fi

# Aliases
if [ -f $HOME/.zsh/aliases.zsh ]; then
  . $HOME/.zsh/aliases.zsh
fi

# Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"

# NVM
#export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
